# Site settings
title: Pdftools Code Samples
description: A collection of code samples and tutorials for Pdftools products
baseurl: "/pdf_code_samples"
url: "https://pdf-tools.github.io"
lang: en

# Theme settings
theme_color: light # light or dark

# Products configuration
products:
  convsrv:
    name: "Conversion Service"
    description: "Scalable document conversion solution"
    icon: "/assets/images/products/conversion-service.svg"
  sdk:
    name: "Pdftools SDK"
    description: "PDF development toolkit"
    icon: "/assets/images/products/pdftools-sdk.svg"
  webviewer:
    name: "Web Viewer"
    description: "Browser-based PDF viewer"
    icon: "/assets/images/products/pdf-viewer-sdk.svg"

# Social Media Links
social:
  facebook: https://www.facebook.com/pdftoolsag
  linkedin: https://www.linkedin.com/company/pdf-tools-ag
  x: https://x.com/pdftoolscom
  discord: https://discord.gg/zE83Kw6bqK

# Google Analytics
google_analytics: G-5ZN922RFGN  # Only enabled in production environment

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
highlighter: rouge
sass:
  style: compressed
  sass_dir: _sass
  
# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - LICENSE

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  tutorials:
    output: true
    permalink: /tutorials/:path/

# Default front matter settings
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_tutorials"
      type: tutorials
    values:
      layout: default
